kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: engine-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: engine
  namespace: asyncy-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
