apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: asyncy/platform-engine
    context: ../platform-engine/  # This is typically the master branch.
    docker:
      dockerfile: Dockerfile
  - image: asyncy/platform-engine-prod
    context: ../platform-engine-prod/  # This is the production branch.
    docker:
      dockerfile: Dockerfile
  - image: asyncy/platform-synapse
    context: ../platform-synapse/
    docker:
      dockerfile: Dockerfile
  - image: asyncy/http
    context: ../http/
    docker:
      dockerfile: Dockerfile
  - image: asyncy/hub-api
    context: ../hub-api/
    docker:
      dockerfile: Dockerfile
  - image: asyncy/hub-sync-temp
    context: ../hub-sync-temp/
    docker:
      dockerfile: Dockerfile
  - image: asyncy/platform-graphql
    context: ../platform-graphql/
    docker:
      dockerfile: Dockerfile
  - image: asyncy/logstreamer
    context: ../logstreamer/
    docker:
      dockerfile: Dockerfile
  - image: asyncy/dashboard-api
    context: ../dashboard-api/
    docker:
      dockerfile: Dockerfile
  - image: asyncy/openapiwatcher
    context: ../openapiwatcher/
    docker:
      dockerfile: Dockerfile
  local: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes/*/*
