apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  namespace: asyncy-system
spec:
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: trinitronx/python-simplehttpserver
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 50m
              memory: 32M
            requests:
              cpu: 10m
              memory: 10M
