apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: engine
  namespace: asyncy-system
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: engine
    spec:
      # nodeSelector:
      #   role: workers
      containers:
      - name: engine
        image: asyncy/platform-engine
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8084
        # resources:
        #   limits:
        #     cpu: 50m
        #     memory: 64M
        #   requests:
        #     cpu: 10m
        #     memory: 10M
        env:
        - name: LOGGER_NAME
          value: asyncy
        - name: LOGGER_LEVEL
          value: debug
        - name: ASYNCY_HTTP_GW_HOST
          value: gateway
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry
              key: sentry_dsn
        - name: POSTGRES
          valueFrom:
            secretKeyRef:
              name: database-url
              key: root-dsn
        - name: ENGINE_HOST
          value: engine
