apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: engine
  namespace: asyncy-system
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: engine
        logstash-enabled: "true"
    spec:
      containers:
      - name: engine
        image: asyncy/platform-engine
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8084
        resources:
          limits:
#            cpu: 50m
            memory: 256M
          requests:
#            cpu: 10m
            memory: 256M
        envFrom:
          - configMapRef:
              name: engine-common
        env:
        - name: APP_ENVIRONMENT
          value: STAGING
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry
              key: sentry_dsn
        - name: POSTGRES_URI
          valueFrom:
            secretKeyRef:
              name: database-url
              key: root-uri-with-search-path
        - name: CLUSTER_CERT
          valueFrom:
            secretKeyRef:
              name: engine-sa-creds
              key: ca.crt
        - name: CLUSTER_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: engine-sa-creds
              key: token
        - name: ENGINE_HOST
          value: engine.asyncy-system.svc.cluster.local
