apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: engine
  namespace: asyncy-system
spec:
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
        - name: engine
          image: asyncy/platform-engine
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 50m
              memory: 64M
            requests:
              cpu: 10m
              memory: 10M
