apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  namespace: asyncy-system
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      # nodeSelector:
      #   role: workers
      containers:
      - name: gateway
        image: asyncy/http:v0.1.0
        args:
        - python
        - -m
        - app.main
        - --logging=debug
        - --debug
        imagePullPolicy: IfNotPresent
        ports:
        - name: public
          containerPort: 8888
        - name: internal
          containerPort: 8889
        # resources:
        #   limits:
        #     cpu: 50m
        #     memory: 64M
        #   requests:
        #     cpu: 10m
        #     memory: 10M
        env:
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry
              key: sentry_dsn
