apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: asyncy-system
spec:
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: asyncy/platform-grafana
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          resources:
            limits:
              cpu: 50m
              memory: 32M
            requests:
              cpu: 10m
              memory: 10M
