apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: graphql
  namespace: asyncy-system
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: graphql
    spec:
      # nodeSelector:
      #   role: workers
      containers:
      - name: graphql
        image: asyncy/platform-graphql
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
        # resources:
        #   limits:
        #     cpu: 500m
        #     memory: 32M
        #   requests:
        #     cpu: 100m
        #     memory: 10M
        env:
        - name: ROOT_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: postgres_conn_string
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: postgres_conn_string  # todo: discuss authenticator, right now, using root creds for it
