apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: asyncy-system
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.0.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 512M
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        env:
          - name: SERVER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SERVER_HOST
            value: "0.0.0.0"
          - name: ELASTICSEARCH_HOSTS
            value: http://elasticsearch:9200
