apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstreamer
  namespace: asyncy-system
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: logstreamer
        logstash-enabled: "true"
    spec:
      # nodeSelector:
      #   role: workers
      containers:
        - name: logstreamer
          image: asyncy/logstreamer
          imagePullPolicy: IfNotPresent
          args:
            - java
            - -Xms128m
            - -Xmx128m
            - -jar
            - /app/target/log-streamer-1.0-SNAPSHOT-jar-with-dependencies.jar
          ports:
            - name: websocket-port
              containerPort: 4444
            - name: control-port
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              memory: 256M
          env:
            - name: DEBUG
              value: "true"
            - name: LOGSTASH_HOST
              value: logstash
            - name: LOGSTASH_PORT
              value: "3232"
