apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metabase
  namespace: asyncy-platform
spec:
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase
          image: metabase/metabase
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          resources:
            limits:
              cpu: 500m
              memory: 256M
            requests:
              cpu: 100m
              memory: 10M
