apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metabase
  namespace: asyncy-system
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
        # resources:
        #   limits:
        #     cpu: 50m
        #     memory: 32M
        #   requests:
        #     cpu: 10m
        #     memory: 10M
        volumeMounts:
        - mountPath: /tmp
          name: metabase-data
        env:
        - name: "MB_DB_FILE"
          value: "/tmp/metabase.db"
      volumes:
      - name: metabase-data
        persistentVolumeClaim:
          claimName: metabase-data
