apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  namespace: asyncy-platform
spec:
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:3.6.3
          imagePullPolicy: Always
          ports:
            - name: mongo
              containerPort: 27017
          resources:
            limits:
              cpu: 500m
              memory: 256M
            requests:
              cpu: 100m
              memory: 10M
