apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  namespace: asyncy-system
spec:
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:3.6.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongo
              containerPort: 27017
          resources:
            limits:
              cpu: 50m
              memory: 32M
            requests:
              cpu: 10m
              memory: 10M
