apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: asyncy-system
spec:
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.3-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
          resources:
            limits:
              cpu: 50m
              memory: 32M
            requests:
              cpu: 10m
              memory: 10M
