apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: asyncy-platform
spec:
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.3-alpine
          imagePullPolicy: Always
          ports:
            - name: postgres
              containerPort: 5432
          resources:
            limits:
              cpu: 500m
              memory: 512M
            requests:
              cpu: 100m
              memory: 10M
