apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  namespace: asyncy-system
spec:
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: asyncy/platform-prometheus
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9090
        # resources:
        #   limits:
        #     cpu: 50m
        #     memory: 32M
        #   requests:
        #     cpu: 10m
        #     memory: 10M
