apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  namespace: asyncy-system
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        # See https://github.com/coreos/prometheus-operator/issues/966.
        # If the container is not run as root, then it can't chmod the /prometheus volume.
        runAsNonRoot: false
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: prometheus
        image: asyncy/platform-prometheus
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9090
        volumeMounts:
          - mountPath: /prometheus
            name: prometheus-data
      volumes:
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data
        # resources:
        #   limits:
        #     cpu: 50m
        #     memory: 32M
        #   requests:
        #     cpu: 10m
        #     memory: 10M
