apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: asyncy-system
spec:
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.7.3-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: rabbitmq
              containerPort: 5672
          resources:
            limits:
              cpu: 50m
              memory: 32M
            requests:
              cpu: 10m
              memory: 10M
