apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: statsd
  namespace: asyncy-system
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: statsd
    spec:
      containers:
      - name: statsd
        image: prom/statsd-exporter:v0.6.0
        imagePullPolicy: IfNotPresent
        args:
        - -statsd.listen-udp=:8125
        - -statsd.listen-udp=:8125
        ports:
        - name: statsd
          containerPort: 8125
        # resources:
        #   limits:
        #     cpu: 50m
        #     memory: 16M
        #   requests:
        #     cpu: 10m
        #     memory: 10M
