apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: synapse
  namespace: asyncy-system
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: synapse
    spec:
      # nodeSelector:
      #   role: workers
      containers:
      - name: synapse
        image: asyncy/platform-synapse
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        # resources:
        #   limits:
        #     cpu: 50m
        #     memory: 64M
        #   requests:
        #     cpu: 10m
        #     memory: 10M
        env:
        - name: POSTGRES
          valueFrom:
            secretKeyRef:
              name: database-url
              key: root-dsn
        - name: CLUSTER_CERT
          valueFrom:
            secretKeyRef:
              name: synapse-sa-creds
              key: ca.crt
        - name: CLUSTER_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: synapse-sa-creds
              key: token
