apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: asyncy-system
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: elasticsearch
