apiVersion: v1
kind: Service
metadata:
  name: engine
  namespace: asyncy-system
  labels:
    app: engine
spec:
  ports:
  - port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: engine
