apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: asyncy-system
  labels:
    app: gateway
spec:
  ports:
  - port: 8888
    name: external
    protocol: TCP
    targetPort: 8888
  - port: 8889
    name: internal
    protocol: TCP
    targetPort: 8889
  selector:
    app: gateway
