apiVersion: v1
kind: Service
metadata:
  name: logstreamer
  namespace: asyncy-system
  labels:
    app: logstreamer
spec:
  ports:
    - port: 4444
      name: websocket-listener
      protocol: TCP
      targetPort: 4444
  selector:
    app: logstreamer
