apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: asyncy-system
  labels:
    app: logstash
spec:
  ports:
  - port: 5044
    name: beats-listener
    protocol: TCP
    targetPort: 5044
  selector:
    app: logstash
