apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-web-and-blog
  namespace: asyncy-system
  labels:
    app: nginx-proxy-web-and-blog
spec:
  ports:
  - port: 8089
    name: http
    protocol: TCP
    targetPort: 8089
  selector:
    app: nginx-proxy-web-and-blog
