apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: asyncy-system
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
