apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: asyncy-system
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: rabbitmq
