apiVersion: v1
kind: Service
metadata:
  name: sync
  namespace: asyncy-system
  labels:
    app: sync
spec:
  ports:
  - port: 5000
    name: external
    protocol: TCP
    targetPort: 5000
  selector:
    app: sync
