apiVersion: v1
kind: Service
metadata:
  name: teamcity
  namespace: asyncy-system
  labels:
    app: teamcity
spec:
  ports:
  - port: 8111
    name: teamcity-main
    protocol: TCP
    targetPort: 8111
  selector:
    app: teamcity
